# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/:title

# Setup
title:            Bikang Peneleh
tagline:          'Kue Tradisional from Surabaya, Aneka Kue Basah, Since 1978, Resep Kue Indonesia'
description:      'Bikang Peneleh Kue Basah Tradisional from Surabaya'
url:              https://www.bikangpeneleh.com
baseurl:          
commentsystem:    google
disqus:           example

author:
  name:           Peneleh
  url:            https://www.bikangpeneleh.com

plugins:
  - jekyll-paginate
paginate:         10

# Custom vars
icon:             /assets/images/peneleh.png
cover:            /assets/images/banner02.jpg

social:

  - icon:         github
    url:          https://github.com/bikangpeneleh
    desc:         Fork me on github

  - icon:         googleplus-alt
    url:          https://plus.google.com/u/0/107675348558921640068
    desc:         Add me on google+

  - icon:         feed
    url:          https://www.bikangpeneleh.com/atom.xml
    desc:         Subscribe to my feed

menu:
  - title:        Home
    url:          /

  - title:        About Us
    url:          /aboutus

  - title:        Contact Us
    url:          /contactus

  - title:        Menu Kue
    url:          /daftar-kue-update-jun-2017

copyright:
  author:         Bikang Peneleh
  url:            https://www.bikangpeneleh.com
  type_title:     All Rights Reserved
  type_url:       

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics: UA-73910380-1 

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
