# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            Bikang Peneleh
tagline:          'blog'
description:      'The Tasteful Of Bikang Peneleh from Surabaya.'
url:              http://bikangpeneleh.github.io
baseurl:          
commentsystem:    google
disqus:           example

author:
  name:           Peneleh
  url:            https://google.com/+bikangpeneleh

paginate:         5

# Custom vars
icon:             /assets/images/peneleh.png
cover:            /assets/images/kue_bikang.jpg

social:

  - icon:         github
    url:          https://github.com/bikangpeneleh
    desc:         Fork me on github

  - icon:         googleplus-alt
    url:          https://google.com/+bikangpeneleh
    desc:         Add me on google+

  - icon:         feed
    url:          http://bikangpeneleh.github.io/atom.xml
    desc:         Subscribe to my feed

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

copyright:
  author:         Peneleh
  url:            http://bikangpeneleh.github.io
  type_title:     Some rights reserved
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
